---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: _outils
  label: Outils
  create: all
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: _clients
  label: Clients
  create: all
  match: "**/*"
- type: directory
  path: _partenaires
  label: Partenaires
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
